### ISSUE TITLE
Deno example in README.md doesn't work with files

### ISSUE THREAD

**Issue by penberg** [libsql/libsql-client-ts#138]
The following fails with Deno:

```
import { createClient } from "https://esm.sh/@libsql/client@0.4.0-pre.2/node";

const config = {
  url: "file:local.db"
};
const db = createClient(config);
const rs = await db.execute("SELECT * FROM users");
console.log(rs);
```

```
error: Uncaught Error: module "@libsql/darwin-arm64" not found
    at require (https://esm.sh/v135/libsql@0.2.0-pre.2/denonext/libsql.mjs:4:178)
    at https://esm.sh/v135/libsql@0.2.0-pre.2/denonext/libsql.mjs:5:1969
    at https://esm.sh/v135/libsql@0.2.0-pre.2/denonext/libsql.mjs:5:452
    at https://esm.sh/v135/libsql@0.2.0-pre.2/denonext/libsql.mjs:5:4899
```

this works, however:

```
import { createClient } from "npm:@libsql/client/node";

const config = {
  url: "file:local.db"
};
const db = createClient(config);
const rs = await db.execute("SELECT * FROM users");
console.log(rs);
penberg@vonneumann deno-example % vi example.ts
penberg@vonneumann deno-example % cat example.ts
//import { createClient } from "https://esm.sh/@libsql/client@0.4.0-pre.2/node";
import { createClient } from "npm:@libsql/client/node";

const config = {
  url: "file:local.db"
};
const db = createClient(config);
const rs = await db.execute("SELECT * FROM users");
console.log(rs);
```

**Comment by bitofbreeze** [comment]
Same thing happened to me using the [Remix vite cloudflare framework](https://remix.run/docs/en/main/future/vite#cloudflare) and running it with node locally. libsql/client seems to think it's in the cloudflare environment.

**Comment by blanklob** [comment]
Same here any update on how you solved with Remix?

**Comment by igorbrasileiro** [comment]
Facing the same issue. The workaround to use `npm:@libsql/client/node` needs to allow ffi.

**Comment by Necmttn** [comment]
Same issue  and i can not use `npm:@libsql/client/node` due to i'm using supabase edge-runtime don't know a way to pass ffi argument

**Comment by alexdatsyuk** [comment]
The problem remains if you try to compile the app with [deno --compile](https://docs.deno.com/runtime/reference/cli/compiler/) or deploy it to [deno deploy](https://deno.com/deploy).

**Comment by fightbulc** [comment]
in the meantime the following is a workaround if you want to deploy to Deno Deploy

```typescript
import type { Client } from 'libsql-core';

interface SqliteConfig {
  url: string;
  authToken?: string;
}

export class Sqlite {
  private client!: Client;

  constructor(private readonly config: SqliteConfig) {}

  async getClient(): Client {
    if (!this.client) {
      await this.createClient();
    }

    return this.client;
  }

  private async createClient() {
    // local db file
    if (this.isFileUrl(this.config.url)) {
      const libsqlNode = await import('libsql-node');

      this.client = libsqlNode.createClient({ url: this.config.url });
      await this.setPragma();

      return this;
    }

    // remote db
    // due to deno limitations we need to use libsql-web
    const libsqlWeb = await import('libsql-web');

    this.client = libsqlWeb.createClient({
      url: this.config.url,
      authToken: this.config.authToken,
    });

    return this;
  }

  private isFileUrl(url: string): boolean {
    return url.startsWith('file:');
  }

  private async setPragma() {
    await this.client.execute('PRAGMA journal_mode = WAL;');
    await this.client.execute('PRAGMA busy_timeout = 5000;');
    await this.client.execute('PRAGMA synchronous = NORMAL;');
    await this.client.execute('PRAGMA cache_size = 2000;');
    await this.client.execute('PRAGMA temp_store = MEMORY;');
    await this.client.execute('PRAGMA foreign_keys = true;');
  }
}
```

**Comment by alexdatsyuk** [comment]
This works, but only in http mode with no support for embedded replicas. The whole point of using Turso is to have embedded replicas for reads in such a simple way.

**Comment by marpe** [comment]
I'm not using deno, but I'm getting the same error together with next:

```
 ⨯ Error [LibsqlError]: URL_SCHEME_NOT_SUPPORTED: The client that uses Web standard APIs supports only "libsql:", "wss:", "ws:", "https:" and "http:" URLs, got "file:". For more information, please read https://github.com/libsql/libsql-client-ts#supported-urls
    at <unknown> (webpack-internal:///(middleware)/./node_modules/@libsql/client/lib-esm/web.js:30)
    at _createClient (webpack-internal:///(middleware)/./node_modules/@libsql/client/lib-esm/web.js:30:15)
    at createClient (webpack-internal:///(middleware)/./node_modules/@libsql/client/lib-esm/web.js:19:12)
    at eval (webpack-internal:///(middleware)/./src/db.ts:16:76)
    at (middleware)/./src/db.ts (file://C:\dev\tmp\spaced\.next\server\src\middleware.js:1401:1)
    at __webpack_require__ (file://C:\dev\tmp\spaced\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://C:\dev\tmp\spaced\.next\server\edge-runtime-webpack.js:285:21)
    at eval (webpack-internal:///(middleware)/./src/auth.ts:8:61)
    at (middleware)/./src/auth.ts (file://C:\dev\tmp\spaced\.next\server\src\middleware.js:1390:1)
    at __webpack_require__ (file://C:\dev\tmp\spaced\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://C:\dev\tmp\spaced\.next\server\edge-runtime-webpack.js:285:21)
```

**Comment by JTRNS** [comment]
Removing the following line: `"deno": "./lib-esm/web.js"` from the `exports` property in  `node_modules/@libsql/client/package.json` has been my most successful workaround so far.

**Comment by y12studio** [comment]
The following script demonstrates that the import statement ```import { createClient } from "@libsql/client/node";``` is compatible with Deno 2.0.2.

```sh
#!/bin/bash
docker run --rm -i denoland/deno:2.0.2 sh <<\EOF
date
env
mkdir myapp
cd myapp
deno init .
deno add npm:@libsql/client@0.14.0
cat <<EOOF > main.ts
import { createClient } from "@libsql/client/node";
const client = createClient({
    url: "file:local.db",
});
await client.batch(
    [
        "CREATE TABLE IF NOT EXISTS users (email TEXT)",
        "INSERT INTO users VALUES ('first@example.com')",
    ],
    "write",
);
const result = await client.execute("SELECT * FROM users");
console.log("Users:", result.rows);
EOOF
echo
echo "==> test 1"
echo
deno run -A main.ts
EOF
```

**Comment by jorgechato** [comment]
Working with **cloudflare workers** and I experience the same issue;
- bun 1.1.31
- @libsql/client 0.14.0

```sh
LibsqlError: URL_SCHEME_NOT_SUPPORTED: The client that uses Web standard APIs supports only "libsql:", "wss:", "ws:", "https:" and "http:" URLs, got "file:". For more information, please read https://github.com/libsql/libsql-client-ts#supported-urls
```

**Comment by edard3v** [comment]
It doesn't work for me T.T. These kinds of things are what make you think a lot about switching to Deno.

**Comment by kj-9** [comment]
opened PR #297 to facilitate our discussion.

Here's a summary of the changes:
- Added a test for Deno to run the example script in CI.
- Simply utilizing `lib-esm/node.js` instead of `lib-esm/web.js` to use a local file or `:memory:` database from Deno.

But this requires additional `--allow-ffi` flag since `lib-esm/node.js` imports [createClient function from sqlite3](https://github.com/tursodatabase/libsql-client-ts/blob/9e6b5b8bb13701bd60d6d06641922d878163b216/packages/libsql-client/src/node.ts#L5).  (which should be treated as a breaking change, I suppose)

At this point, I'm uncertain about the next steps. I considered dynamically importing createClient from sqlite3, but this approach would necessitate making the function asynchronous.

**Comment by edard3v** [comment]
Sorry bro, I got tired of trying things, if you want I'll leave the repository here, it currently works remotely, but not locally.

https://github.com/edard3v/template-deno

**Comment by williamukoh** [comment]
> It doesn't work for me T.T. These kinds of things are what make you think a lot about switching to Deno.

I agree. But Deno is becoming more solid with every release. And kinks like these, will be ironed out

**Comment by edard3v** [comment]
@williamukoh Igualmente ahora tengo claro que el problema no es de Deno si no de turso. Ando usando mientrastanto Neon-postgres y funciona perfectamente. Es una pena porque en verdad me gusta mucho Turso-sqlite
